[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_RUNTIME = "nodejs"
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  included_files = ["next.config.mjs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "next"
