# Netlify configuration for Next.js app (SSR + API routes)
[build]
  command = "npm run build"
  publish = ".next"
  environment = { NEXT_PUBLIC_SUPABASE_URL = "", NEXT_PUBLIC_SUPABASE_ANON_KEY = "" }

[dev]
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to Next.js handler
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# If you want to fallback to static export, use the commented config below:
# [build]
#   command = "npm run export"
#   publish = "out"
#
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
