apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjs-config
  namespace: nextjs-app
  labels:
    app: nextjs-app
data:
  NODE_ENV: "production"
  PORT: "3000"
  SUPABASE_URL: "https://xqkqeluodrjeammwdjro.supabase.co"
  NEXT_PUBLIC_SUPABASE_URL: "https://xqkqeluodrjeammwdjro.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxa3FlbHVvZHJqZWFtbXdkanJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Mjk3ODYsImV4cCI6MjA2ODAwNTc4Nn0.I8b1PoXFaP6f0grAH7HqdTe6jolE8oE_IIIF0Xe0RTc"
